enable signal output if disabled in the Simulink model

diff --git a/falcaun b/falcaun
--- a/falcaun
+++ b/falcaun
@@ -13,39 +13,40 @@
 readonly JAR_NAME=org/group_mmm/falcaun/1.0-SNAPSHOT/falcaun-1.0-SNAPSHOT-jar-with-dependencies.jar
 
 if [ -z "$MATLAB_HOME" ]; then
-    echo "Error: environment variable MATLAB_HOME is not set"
-    exit 1
+  echo "Error: environment variable MATLAB_HOME is not set"
+  exit 1
 fi
 
 case "$(uname)" in
-    Darwin)
-        arch=maci64
-        if java="$(/usr/libexec/java_home -v '1.8')/bin/java"; then
-            echo "Java 8 found at $java";
-        elif java="$(/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home -v '1.8')/bin/java"; then
-            echo "Java 8 found at $java";
-        else
-            echo "Error: Java 8 did not found";
-            exit 1;
-        fi
-        ;;
-    Linux)
-        arch=glnxa64
-        if java=$(find /usr/lib/jvm/java-8-openjdk* -name java -type f) 2>/dev/null; then
-            echo "Java 8 found at $java";
-        else
-            echo "Error: Java 8 did not found";
-            exit 1;
-        fi
-        ;;
-    *)
-        echo "Error: Unknown architecture $(uname)"
-        exit 1
+Darwin)
+  arch=maci64
+  if java="$(/usr/libexec/java_home -v '1.8')/bin/java"; then
+    echo "Java 8 found at $java"
+  elif java="$(/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home -v '1.8')/bin/java"; then
+    echo "Java 8 found at $java"
+  else
+    echo "Error: Java 8 did not found"
+    exit 1
+  fi
+  ;;
+Linux)
+  arch=glnxa64
+  if java=$(find /usr/lib/jvm/java-8-openjdk* -name java -type f) 2>/dev/null; then
+    echo "Java 8 found at $java"
+  else
+    echo "Error: Java 8 did not found"
+    exit 1
+  fi
+  ;;
+*)
+  echo "Error: Unknown architecture $(uname)"
+  exit 1
+  ;;
 esac
 
-if ! (command -v mvn > /dev/null 2>&1 ); then
-    echo "Error: Maven must be installed"
-    exit 1
+if ! (command -v mvn >/dev/null 2>&1); then
+  echo "Error: Maven must be installed"
+  exit 1
 fi
 
 maven_repo_path="$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)"
